#------------------------------------------------------------
# common
#------------------------------------------------------------

pg: &pg
  adapter:  postgresql
  host:     localhost
  port:     5432
  encoding: utf8
  template: template0

#------------------------------------------------------------
# environments
#------------------------------------------------------------

development:
  <<: *pg
  host:     localhost
  username: dbuser
  password: dbuser
  database: wwsmd_development


test:
  <<: *pg
  username: dbuser
  password: dbuser
  database: wwsmd_test

production:
  <<: *pg
  database: wwsmd_production

